server {
    listen 80;
    listen [::]:80;
    server_name green-api.metairony.dev;

    root /var/www/green-api;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript image/x-icon;
    gzip_min_length 1024;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|js)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location = /favicon.ico {
        expires 30d;
        add_header Cache-Control "public";
        log_not_found off;
    }
}
